[project]
name = "mysg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gstreamer-bundle==1.28.0",
    "onnxruntime-gpu==1.25.0",
    "opencv-python>=5.0.0.93",
    "fastapi>=0.115",
    "uvicorn>=0.30",
    "websockets>=13.0",
]
